services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - Default_region_name = us-east-1
      - AWS_Access _Key_ID = Fake
      - AWS_Secret_Access_Key = Fake